/** Single source of truth for the CogniRun questions library (see README.md). */
export const QUESTION_LIBRARY = {
  version: 1,
  categories: ['trivia', 'logic', 'math'],
  questions: [
    {
      id: 'trivia-1',
      category: 'trivia',
      prompt: 'What is the chemical symbol for gold?',
      answer: 'Au',
      options: ['Au', 'Ag', 'Go', 'Gd'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-2',
      category: 'trivia',
      prompt: 'How many continents are there?',
      answer: '7',
      options: ['5', '6', '7', '8'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-3',
      category: 'trivia',
      prompt: 'What is the capital of Japan?',
      answer: 'Tokyo',
      options: ['Kyoto', 'Tokyo', 'Osaka', 'Sapporo'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-4',
      category: 'trivia',
      prompt: 'Which is the largest planet in the Solar System?',
      answer: 'Jupiter',
      options: ['Saturn', 'Neptune', 'Jupiter', 'Earth'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-5',
      category: 'trivia',
      prompt: 'Who painted the Mona Lisa?',
      answer: 'Leonardo da Vinci',
      options: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-6',
      category: 'trivia',
      prompt: 'Which is the largest ocean on Earth?',
      answer: 'Pacific',
      options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-7',
      category: 'trivia',
      prompt: 'How many players from one football team are on the pitch at kick-off?',
      answer: '11',
      options: ['9', '10', '11', '12'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-8',
      category: 'trivia',
      prompt: 'Which gas do plants absorb from the air for photosynthesis?',
      answer: 'Carbon dioxide',
      options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
      difficulty: 'easy',
    },
    {
      id: 'trivia-9',
      category: 'trivia',
      prompt: 'Which country gave the Statue of Liberty to the United States?',
      answer: 'France',
      options: ['Britain', 'France', 'Spain', 'Italy'],
      difficulty: 'medium',
    },
    {
      id: 'trivia-10',
      category: 'trivia',
      prompt: 'What is the hardest naturally occurring substance?',
      answer: 'Diamond',
      options: ['Quartz', 'Steel', 'Diamond', 'Granite'],
      difficulty: 'medium',
    },
    {
      id: 'logic-1',
      category: 'logic',
      prompt: 'All roses are flowers. Some flowers fade quickly. Does it follow that some roses fade quickly?',
      answer: 'No — the flowers that fade quickly need not be roses.',
      difficulty: 'medium',
    },
    {
      id: 'logic-2',
      category: 'logic',
      prompt: 'If it rains, the match is cancelled. The match was not cancelled. Did it rain?',
      answer: 'No — if it had rained the match would have been cancelled.',
      difficulty: 'easy',
    },
    {
      id: 'logic-3',
      category: 'logic',
      prompt: 'Anna is taller than Ben. Ben is taller than Carl. Who is shortest?',
      answer: 'Carl',
      options: ['Anna', 'Ben', 'Carl'],
      difficulty: 'easy',
    },
    {
      id: 'logic-4',
      category: 'logic',
      prompt: 'Every student passed the exam. Dana is a student. Did Dana pass?',
      answer: 'Yes',
      options: ['Yes', 'No', 'Cannot tell'],
      difficulty: 'easy',
    },
    {
      id: 'logic-5',
      category: 'logic',
      prompt: 'No cats are dogs. Rex is a dog. Is Rex a cat?',
      answer: 'No',
      options: ['Yes', 'No', 'Cannot tell'],
      difficulty: 'easy',
    },
    {
      id: 'logic-6',
      category: 'logic',
      prompt: 'If the alarm rings, everyone leaves the building. Everyone left. Did the alarm necessarily ring?',
      answer: 'No — they could have left for another reason.',
      difficulty: 'medium',
    },
    {
      id: 'logic-7',
      category: 'logic',
      prompt: 'Some birds cannot fly. Penguins are birds. Does it follow that penguins cannot fly?',
      answer: 'No — the premises do not say which birds cannot fly.',
      difficulty: 'hard',
    },
    {
      id: 'logic-8',
      category: 'logic',
      prompt: 'Mia is either at work or at home. She is not at home. Where is she?',
      answer: 'At work',
      options: ['At work', 'At home', 'Cannot tell'],
      difficulty: 'easy',
    },
    {
      id: 'logic-9',
      category: 'logic',
      prompt: 'All squares are rectangles. Is every rectangle a square?',
      answer: 'No',
      options: ['Yes', 'No', 'Cannot tell'],
      difficulty: 'easy',
    },
    {
      id: 'logic-10',
      category: 'logic',
      prompt: 'Tom runs faster than Sam. Sam runs faster than Joe. Who wins a race between Tom and Joe?',
      answer: 'Tom',
      options: ['Tom', 'Joe', 'Cannot tell'],
      difficulty: 'easy',
    },
    {
      id: 'math-1',
      category: 'math',
      prompt: 'What is 7 x 8?',
      answer: '56',
      options: ['48', '54', '56', '64'],
      difficulty: 'easy',
    },
    {
      id: 'math-2',
      category: 'math',
      prompt: 'What is 15% of 200?',
      answer: '30',
      options: ['15', '20', '30', '35'],
      difficulty: 'easy',
    },
    {
      id: 'math-3',
      category: 'math',
      prompt: 'What is 144 divided by 12?',
      answer: '12',
      options: ['11', '12', '14', '16'],
      difficulty: 'easy',
    },
    {
      id: 'math-4',
      category: 'math',
      prompt: 'What is half of 3/4?',
      answer: '3/8',
      options: ['1/2', '3/8', '2/3', '1/4'],
      difficulty: 'medium',
    },
    {
      id: 'math-5',
      category: 'math',
      prompt: 'What is 25 + 38?',
      answer: '63',
      options: ['53', '62', '63', '73'],
      difficulty: 'easy',
    },
    {
      id: 'math-6',
      category: 'math',
      prompt: 'You run 3 km in 18 minutes. What is your pace per kilometer?',
      answer: '6 minutes',
      options: ['5 minutes', '6 minutes', '6:30', '9 minutes'],
      difficulty: 'medium',
    },
    {
      id: 'math-7',
      category: 'math',
      prompt: 'What is 2 to the power of 6?',
      answer: '64',
      options: ['32', '48', '64', '128'],
      difficulty: 'medium',
    },
    {
      id: 'math-8',
      category: 'math',
      prompt: 'What is 100 - 43?',
      answer: '57',
      options: ['47', '53', '57', '67'],
      difficulty: 'easy',
    },
    {
      id: 'math-9',
      category: 'math',
      prompt: 'What comes next: 2, 6, 12, 20, ...?',
      answer: '30',
      options: ['26', '28', '30', '32'],
      difficulty: 'hard',
    },
    {
      id: 'math-10',
      category: 'math',
      prompt: 'What is the average of 4, 9 and 14?',
      answer: '9',
      options: ['8', '9', '10', '12'],
      difficulty: 'medium',
    },
  ],
};
